// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozonva/ova-person-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	person "github.com/ozonva/ova-person-api/internal/models"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddPersons mocks base method.
func (m *MockRepo) AddPersons(arg0 []person.Person) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPersons", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPersons indicates an expected call of AddPersons.
func (mr *MockRepoMockRecorder) AddPersons(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPersons", reflect.TypeOf((*MockRepo)(nil).AddPersons), arg0)
}

// DescribePerson mocks base method.
func (m *MockRepo) DescribePerson(arg0 uint64) (*person.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribePerson", arg0)
	ret0, _ := ret[0].(*person.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribePerson indicates an expected call of DescribePerson.
func (mr *MockRepoMockRecorder) DescribePerson(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribePerson", reflect.TypeOf((*MockRepo)(nil).DescribePerson), arg0)
}

// ListPersons mocks base method.
func (m *MockRepo) ListPersons(arg0, arg1 uint64) ([]person.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPersons", arg0, arg1)
	ret0, _ := ret[0].([]person.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPersons indicates an expected call of ListPersons.
func (mr *MockRepoMockRecorder) ListPersons(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPersons", reflect.TypeOf((*MockRepo)(nil).ListPersons), arg0, arg1)
}
